#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Format-RIFF
version:      1.0.0
version_from: 
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
