#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Format-RIFF
version:      0.05
version_from: lib/File/Format/RIFF/Version.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
